### ISSUE TITLE
Add horizontal padding on mobile containers.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/IBI-Site#4]
We want to avoid cases where text goes from edge to edge.
![screenshot from 2016-07-28 13-53-40](https://cloud.githubusercontent.com/assets/1911594/17211605/bafc6978-54ca-11e6-8e38-72e29f31e608.png)

There needs to be padding of around `1em` or perhaps a bit more on the sides to make sure text is not being blocked by someones hand while holding the phone.

**Comment by iliyaM** [comment]
fixed
